name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build project
      run: npm run build

    - name: Build Docker image
      run: docker build -t vue-pdf-annotate .

    - name: Run Docker container
      run: |
        docker run -d -p 5000:80 vue-pdf-annotate
        sleep 10 # wait for the container to start
        docker cp $(docker ps -ql):/usr/share/nginx/html ./dist
        docker stop $(docker ps -ql)

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
